[package]
name = "genet-filter"
version = "0.1.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]
edition = "2018"
publish = false

[dependencies]
failure = "0.1"
serde = "1"
serde_json = "1"
num-bigint = "0.2"
num-traits = "0.2"
pest = "2"
pest_derive = "2"
hwaddr = "0.1"
arrayref = "0.3"
genet-abi = "0.5.0"
